config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :albums

  root 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :songs

  # Case insensitive prefix search
  def self.search(query)
    where('lower(name) LIKE ?', "#{query.downcase}%")
  end

  def artist_name
    artist.name
  end

  def description
    "#{songs.count} songs by #{artist_name}"
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    if params[:query].present?
      @albums = Album.search(params[:query]).includes(:artist)
    end

    @albums ||= Album.all.includes(:artist)
  end

  def show
    @album = Album.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def app_name
    Rails.application.config.session_options[:key].sub(/^_/,'').sub(/_session/,'')
  end

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end

  def active_if_on_page(controller, action)
    'active' if on_page(controller, action)
  end
  
  def on_page(controller = params[:controller], action)
    params[:controller] == controller.to_s and 
        params[:action] == action.to_s
  end
  
  # def link_to_add_fields(name, f, association)
  #   new_object = f.object.send(association).klass.new
  #   id = new_object.object_id
  #   fields = f.fields_for(association, new_object, child_index: id) do |builder|
  #     render(association.to_s.singularize + "_fields", f: builder)
  #   end
  #   link_to(name, '#', class: "add_fields button small round", data: {id: id, fields: fields.gsub("\n", "")})
  # end
end

app/views/albums/index.slim
h1.center Albums

= form_tag albums_path, method: 'get' do
  .flexy-input-form
    = text_field_tag :query, params[:query], placeholder: "Search albums...", class: 'flexy-input-field'
    = button_tag "Search", class: 'btn btn-large flexy-input-button'

- @albums.each do |album|
  = link_to album do
    .card-panel.album
      .album__title
        = album.name

      .album__description
        = album.description

app/views/albums/show.slim
.album-details

  h1= @album.name

  ol
    - @album.songs.each do |song|
      li= song.name

app/views/layouts/_footer.slim
/ ul
/   / li
/     / = image_tag 'client_logo.jpg'
/   li
/     = "Copyright #{Date.today.year} "
/     = link_to "Client Company, Inc.", 'http://www.example.com'
/   li
/     | Website by 
/     = link_to "Neurodynamic", "http://www.neurodynamic.online"
/   / li
/     / - if admin_signed_in?
/     /   = "Logged in as #{current_admin.email}"
/     /   | |
/     /   = link_to "Logout", destroy_admin_session_path, method: :delete
/     / - else
/     /   = link_to "Admin Login", new_admin_session_path

app/views/layouts/_header.slim
nav
  ul.left
    li
      h1= link_to app_name, root_path
  ul.right
    li= link_to "Link 1", "#"
/     - if admin_signed_in?
/       li class=active_if_something
/         = link_to 'Something Restricted', something_restricted_path

app/views/layouts/application.slim
doctype html
html lang="en" 
  head
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : @app_name
    - if Rails.env.development?
      = favicon_link_tag 'development_favicon.ico'
    - else
      = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .page-wrapper
      header= render 'layouts/header'

      main id="#{params[:controller]}-#{params[:action]}"
        .responsive-margin-container
          = yield

      footer= render 'layouts/footer'

    - if Rails.env.development?
      #development-indicator
        = link_to 'Development Mode', '#', class: 'support'

    = render 'shared/google_analytics'